### ISSUE TITLE
Piss Reed off by making lots of issues

### ISSUE THREAD

**Issue by dylnuge** [acm-uiuc/treasure-chest#13]
The issue tracker needs more issues so that Reed comes in here and yells at me more.

We like his company. <3 you Reeeeed

**Comment by chorn21** [comment]
Pissing Reed off more by writing this comment just to say that I like this issue.

**Comment by dylnuge** [comment]
@chorn21 has the right idea. This comment also dedicated to resolving this issue.

**Comment by reedlabotz** [comment]
Installed github filter in gmail.

**Comment by dylnuge** [comment]
Repoening issue, as Reed has not yet visited the office, therefore bug still persists in current working branch.

**Comment by dylnuge** [comment]
Reed is in the office now. Issue closed.
