### ISSUE TITLE
Polish site layout and navigation

### ISSUE THREAD

**Issue by dylnuge** [acm-uiuc/treasure-chest#22]
The site should look a lot prettier. Some changes that can be made:
- Move login so it doesn't look like another link
- Import the ACM css from Liquid so the site has the ACM L&F
- Organize the links so that Treasure Chest has a simpler navigation system
- Create a more useful home page

**Comment by chorn21** [comment]
You're hilarious.

Caroline Horn
University of Illinois at Urbana-Champaign - Mathematics & Computer Science - Undergrad
chorn21@gmail.com

**Comment by dylnuge** [comment]
For now the site nav is where I want it to be for this milestone. It isn't final, so I'll open another issue to fix this for the next major milestone.
